# Generated by Django 2.2.7 on 2020-07-01 04:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import etl.models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Errore',
            },
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': 'Carga de Archivo'},
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=etl.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.ErrorType')),
            ],
            options={
                'verbose_name': 'Tabla de Errore',
            },
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.ErrorLog'),
        ),
    ]
